version: '3.8'

services:
  backend:
    build: ./services/backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appdb
    volumes:
      - ./services/backend/app:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 --env-file /app/src/.env
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend/app:/app'
      - 'appnode_modules:/app/node_modules'
    ports:
      - 8081:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  appnode_modules: